name: eventure
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  acter_avatar: ^2.0.1+1
  animated_bottom_navigation_bar: ^1.4.0
  animated_snack_bar: ^0.4.0
  animated_splash_screen: ^1.3.0
  avatar_stack: ^3.0.0
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.5.0
  cupertino_icons: ^1.0.8
  custom_calender_picker: ^0.1.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_messaging: ^15.2.4
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.1
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  google_sign_in: ^6.2.2
  intl: ^0.19.0
  loading_indicator: ^3.1.1
  local_auth: ^2.3.0
  share_plus: ^10.1.4
  shared_preferences: ^2.3.5
  skeletonizer: ^1.4.2
  timeago: ^3.7.0
  top_snackbar_flutter: ^3.2.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lottie: ^3.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
